### ISSUE TITLE
Decouple generated filenames from hosts

### ISSUE THREAD

**Issue by shawnw** [udem-dlteam/ribbit#16]
Currently, the name of the host is used both for the directory in the hosts tree to look for a rvm file, and the file extension to use. `./rsc -t N foo.scm` looks for `hosts/N/rvm.N` and creates `foo.scm.N`.

It would be nice for there to be a way to map a name to a different extension - so you can have multiple targets using the same language but different implementations, and better handle cases where the extension is used by multiple languages (Like `.ml` being used by ocaml and standard ML).

Some languages might have trouble with source files like `foo.scm.N` instead of `foo.N`, too, so a generic way to transform filenames might be useful as well.

**Comment by feeley** [comment]
It is always possible to choose the output file name with the `-o` option so I don't mind the `foo.scm.N` default.

I like using the extension to specify the language because those names are short, well known, and usually unambiguous.  I don't think the specific case of `.ml` you mention is correct because OCaml uses `.ml` and SML/NJ uses `.sml` if I recall correctly.  A real issue is for `.m` which is used by Mathematica, Matlab, Mercury and Objective-C.

The scripts should implement a map from the target name to the extension (ideally just the "encoding" script).  At the same time I think the target name should be the extension if that is unambiguous.  So both `-t matlab` and `-t objc` would generate a `.m` file.

For supporting variants of a given language there could be `-t lang/variant`.  These could coexist with `-t lang` that would default to one of them or be a "generic" version of the host language that doesn't use implementation specific optimizations.  For example `-t c` would generate plain vanilla C code and `-t c/gcc` and `-t c/clang` could use extensions of these compilers.  This naming scheme would allow additional levels, such as `-t c/gcc/x86` to specify the underlying platform (this is not a suggestion to do that, I am merely pointing out there is a way to extend this in the future).

**Comment by feeley** [comment]
I'll work on this next, since this is causing problems for the `ml` target.  I think I will replace the `foo.scm.T` output filename (where T is the target) with `foo.T`, with the exception of the `scm` target because this would overwrite the source file.

**Comment by lassik** [comment]
> OCaml uses `.ml` and SML/NJ uses `.sml` if I recall correctly.

Yes.
