### ISSUE TITLE
Have a way to specify escaped characters in bytecode on a per-target basis

### ISSUE THREAD

**Issue by shawnw** [udem-dlteam/ribbit#17]
Instead of the current treat-all-targets-the-same approach.

Target A might need `$`'s escaped to `\$`, but doing that in Target B causes an error when you try to run it, for example. Or there are languages like SQL where backslash isn't the escape character.

Use a file in the `hosts/N` directories to controls escapes? Maybe an executable filter script that the stringified bytecode is run through before being inserted into the rvm file...

**Comment by feeley** [comment]
You have a valid point and I have been thinking about this for some time.  Your idea is good for portability, so that the target directory can contain the logic for properly encoding the compacted RVM code with the appropriate escapes.  In the case of the POSIX shell target this encoding means converting each character to its decimal ASCII code.  Similarly, other targets may need to encode the compacted RVM code beyond just escaping characters.  This "encoding" script should probably take care of combining the encoding with the RVM implementation because the string to replace will depend on the encoding.  Currently this is partly done in the `rsc` script, but that's the wrong place for it.

On a related note, I also want to allow backends that are not based on an implementation of the RVM, for example native x86 or ARM machine code.  So the target selection has to be communicated somehow to `rsc.scm`.  For this I plan to add a `declare` form that is prepended to the compiled source code.  For example `(declare (target x86))` .  This information will be available in the `cond-expand` form.

These things will need more thought, but that's a good first approximation.
