### ISSUE TITLE
How to add host functions?

### ISSUE THREAD

**Issue by bentxt** [udem-dlteam/ribbit#25]
Is there is a simple way to add a function from the host platform? 

Something like `##inline-host-statement` or `##inline-host-expression` from Gambit Scheme.

**Comment by feeley** [comment]
That is not currently possible.  Such an extension is not conceptually difficult (and is on the TODO), but its implementation is not simple because each `##inline-host-...` requires adding host code to the RVM.  Currently the only change that is performed on the RVM source code is the injection of the string representing the compacted RVM code.  This is done by the `rsc` shell script using a simple "replace string X by string Y" operation.  For `##inline-host-...` it would require a more complex process that adds new primitives to the builtin primitives.  This operation is host language specific, because each RVM implementation can implement primitives the way that is most convenient.  For example, here is how the JavaScript RVM implements the primitives:

```
primitives = [
  prim3((z, y, x) => [x, y, z]),
  prim1((x) => x),
  () => (pop(), true),
  () => { let y = pop(); pop(); return push(y); },
  () => push([pop()[0],stack,1]),
  prim1((x) => to_bool(is_rib(x))),
  prim1((x) => x[0]),
  prim1((x) => x[1]),
  prim1((x) => x[2]),
  prim2((y, x) => x[0]=y),
  prim2((y, x) => x[1]=y),
  prim2((y, x) => x[2]=y),
  prim2((y, x) => to_bool(x===y)),
  prim2((y, x) => to_bool(x<y)),
  prim2((y, x) => x+y),
  prim2((y, x) => x-y),
  prim2((y, x) => x*y),
  prim2((y, x) => x/y|0),
  getchar,
  prim1(putchar),
  () => pop() && halt() // will crash with error on != 0
];
```

Here is how the Lua RVM does it:

```
local primitives = {
   prim3(rib), -- 0
   prim1(function(x) return x end), -- 1
   pop, -- 2
   arg2, -- 3
   close, -- 4
   prim1(function(x) return to_bool(is_rib(x)) end), -- 5
   prim1(function(x) return x[1] end), -- 6
   prim1(function(x) return x[2] end), -- 7
   prim1(function(x) return x[3] end), -- 8
   prim2(f0s), -- 9
   prim2(f1s), -- 10
   prim2(f2s), -- 11
   prim2(function(x,y) return to_bool(x == y) end), -- 12
   prim2(function(x,y) return to_bool(x<y) end), -- 13
   prim2(function(x,y) return x + y end), -- 14
   prim2(function(x,y) return x - y end), -- 15
   prim2(function(x,y) return x * y end), -- 16
   prim2(quotient), -- 17
   getchar, -- 18
   prim1(putchar), -- 19
   prim1(os.exit) -- 20
}
```

And here is how the C RVM does it:

```
void prim(int no) {
  switch (no) {
  case 0: { // rib
    obj new_rib = TAG_RIB(alloc_rib(NUM_0, NUM_0, NUM_0));
    PRIM3();
    CAR(new_rib) = x;
    CDR(new_rib) = y;
    TAG(new_rib) = z;
    push2(new_rib, PAIR_TAG);
    break;
  }
  case 1: { // id
    PRIM1();
    push2(x, PAIR_TAG);
    break;
  }
...
  case 20: { // exit
    PRIM1();
    vm_exit(NUM(x));
    break;
  }
  default: {
    vm_exit(EXIT_ILLEGAL_INSTR);
  }
  }
}
```

So some part of the Ribbit compiler (either `rsc.scm`, the `rsc` script, or something new) would need to know how to extend these pieces of code with new primitives, using a syntax and structure that is specific to that host RVM implementation (using `primN(function(...) return ... end` in Lua, and `case X: ...` in C).  I would prefer not doing this in `rsc.scm` or the `rsc` script, because that adds a host language dependency in the main part of the compiler.  Probably the best would be to implement this as a script or Scheme program that is right next to the RVM implementation, for example `src/c/rvm-gen.scm` for the C RVM.  But how does `rsc.scm` communicate with `rvm-gen.scm`?  What information does it need to send and in what format?  As an example, for the C RVM it will be needed to add `#include ...` to the C code to be able to call the functions that are referred to by the `##inline-host-...`.  So for this there is probably a need for a `##inline-host-declaration` form to add toplevel code to the RVM implementation.

Also, ideally the system should be powerful enough to *remove* primitives that are not used by the program (for example not implementing the `exit` primitive if it is never called by the source program).

**Comment by tluyben** [comment]
Is this pull request 

https://github.com/udem-dlteam/ribbit/pull/30 

not the solution to this?

**Comment by leo-ard** [comment]
@tluyben  @bentxt  Yes indeed ! We are currently working on extending the RVM with primitives at compile time (and even at runtime for hosts that permits it). Here is a sneak peek of what we have in mind (and works at the moment on the PR). Note that everything is WIP and nothing is fixed at the moment :)

Here is an example to implement a simple `square` primitive targeting 3 languages. This code can compile to Python, JavaScript and C hosts. 
```scheme
(cond-expand
  ((host py)
   (define-primitive (square a)
                     "lambda: push(pop() ** 2),"))
  ((host js)
   (define-primitive (square a)
                     "() => push(pop() ** 2)"))
  ((host c)
   (define-primitive (square a)
                     "{PRIM1();push2(TAG_NUM((NUM(x) * NUM(x))), PAIR_TAG);break;}")))

(putchar (square 6)) ;; Prints '$' (code 36)
```

We achieve this by adding annotations to RVMs, for example, here are some of the annotations for `c` and `js` RVMs. Using those, we generate specialized hosts containing the primitives defined with `define-primitive`. All annotations start with `@@(` and end with `)@@` and contain lisp-like annotations.
In c, (also available [here](https://github.com/udem-dlteam/ribbit/blob/2144c13fd216a84d9c7c29e609888e09248f38f0/src/host/c/rvm.c#L402)) :
```c
void prim(int no) {
  switch (no) { 
  // @@(primitives (gen "case " index ":" body) 
  case 0: // @@(primitive (rib a b c)
  {
    obj new_rib = TAG_RIB(alloc_rib(NUM_0, NUM_0, NUM_0));
    PRIM3();
    CAR(new_rib) = x;
    CDR(new_rib) = y;
    TAG(new_rib) = z;
    push2(new_rib, PAIR_TAG);
    break;
    
  } // )@@
  case 1: // @@(primitive (id x)
  {
    PRIM1();
    push2(x, PAIR_TAG);
    break;
  } // )@@
  ...
  // ) @@
```
In js (also available [here](https://github.com/udem-dlteam/ribbit/blob/2144c13fd216a84d9c7c29e609888e09248f38f0/src/host/js/rvm.js#L312)) :
```js
primitives = [
// @@(primitives (gen body)
  prim3((z, y, x) => [x, y, z]),                    //  @@(primitive (rib a b c))@@
  prim1((x) => x),                                  //  @@(primitive (id x))@@
  () => (pop(), true),                              //  @@(primitive (arg1 x y))@@
  () => { let y = pop(); pop(); return push(y); },  //  @@(primitive (arg2 x y))@@
  () => push([pop()[0],stack,1]),                   //  @@(primitive (close rib))@@
  prim1((x) => bool_to_rib(is_rib(x))),             //  @@(primitive (rib? rib) (use bool_to_rib))@@
  prim1((x) => x[0]),                               //  @@(primitive (field0 rib))@@
  prim1((x) => x[1]),                               //  @@(primitive (field1 rib))@@
  prim1((x) => x[2]),                               //  @@(primitive (field2 rib))@@
  prim2((y, x) => x[0]=y),                          //  @@(primitive (field0-set! rib))@@
  prim2((y, x) => x[1]=y),                          //  @@(primitive (field1-set! rib))@@
  prim2((y, x) => x[2]=y),                          //  @@(primitive (field2-set! rib))@@
  prim2((y, x) => bool_to_rib(x===y)),              //  @@(primitive (eqv? x y) (use bool_to_rib))@@
  prim2((y, x) => bool_to_rib(x<y)),                //  @@(primitive (< x y) (use bool_to_rib))@@
  prim2((y, x) => x+y),                             //  @@(primitive (+ x y))@@
  prim2((y, x) => x-y),                             //  @@(primitive (- x y))@@
  prim2((y, x) => x*y),                             //  @@(primitive (* x y))@@
  prim2((y, x) => x/y|0),                           //  @@(primitive (quotient x y))@@
  getchar,                                          //  @@(primitive (getchar))@@
  prim1(putchar),                                   //  @@(primitive (putchar c))@@
  () => pop() && halt(),//will crash with error on != 0 @@(primitive (exit n))@@
// )@@
];
```

Here is a last example (available [here](https://github.com/udem-dlteam/ribbit/blob/leo-ard/primitives/src/examples/print_file.scm)) to create a program that simply prints a file passed as an argument. You can compile this file with `gsi -t js -l max examples/print_file.scm -o print_file.js` and run it with `node print_file.js file_to_print`. Here is the content : 

```scheme
(cond-expand
  ((host js)
   (define-primitive (string-from-file path)
                     (use rib_to_str str_to_rib)
                     "() => {try{return push(str_to_rib(node_fs.readFileSync(rib_to_str(pop()), 'utf-8').toString()))}catch{ return push(FALSE)}},")

   (define-primitive (command-line)
                     (use list_to_rib)
                     "() => push(list_to_rib(process.argv.splice(1))),")))

(let ((filename (cadr (command-line))))  ;; take the first argument of the script
  (display (string-append filename ":\n")) 
  (display (string-from-file filename))) ;; display the file
```

Note the use of the `use` keyword inside the `define-primitive`. This tells the RVM that the primitive needs certain "features" to be enabled. For example, the `list_to_rib` function. This function is defined inside of the javascript RVM [here](https://github.com/udem-dlteam/ribbit/blob/2144c13fd216a84d9c7c29e609888e09248f38f0/src/host/js/rvm.js#L203) and let the user convert a javascript list to a ribbit one. It is wrapped with an annotation, removing this code if we don't need it.

As this is all WIP, we can benefit from some feedback or more questions !

**Comment by tluyben** [comment]
This helps a lot @leo-ard ; I was trying something along the lines of what @feeley did above here by creating a new primitive hardcoded called native-eval, which, for js/python runtimes would simply run their respective eval, however, I got stuck on list_to_rib etc to marshall from internal/native structures. It wouldn't work at compile time, but would at least give the freedom to add host calls fast. Your work is definitely more robust; good timing!
