### ISSUE TITLE
lightweight, shareable datatypes

### ISSUE THREAD

**Issue by bentaca** [udem-dlteam/ribbit#43]
Question:
What do you think about simple and lightweight data types (simple string type and a list list type) that are sharable between Scheme and the host without the need for conversion?

Shared, bidirectionally usable data types:
`string`, `float`, `array`

Reasoning:

It is really great to see how ribbit can handle real Scheme code on all those different hosts with this simple runtime. With the new 'feature' system' it is possible to interweave Scheme and its recursive deeply nested and self-evaluating nature with all those different mostly down-to earth imperative hosts.

The price you pay for this integration are datatype conversion for all types. But in my day I do a lot of simple imperative-heavy scripting and in this world you deal with simple string types (maybe numbers) and lists (arrays), and frankly that is good enough for alot of tasks. There is very little nested data manipulation and recursion involved. 

In this case Ribbit would demand alot of data conversion from the host system, which is not really necessary, or at least not worth the trouble. 

So I think there some overhead and therefore it would be great to have at least one string-like sharable datatype.

**Comment by leo-ard** [comment]
This is a good question ! 

We were thinking of integrating a system of `foreign` types. This type represent an unconverted value in the host language. This would let us interact with the host language more directly, leverage the cost of conversion, and speed up vectors as they are encoded with a linked-list (and have `O(n)` access time, which is quite bad). It would work a little bit like this (on js host) : 

```scheme
(define-primitive 
  (make-vector size default)
  (use scm2host foreign)
  "prim2((def, size) => foreign(Array(size).fill(scm2host(def))) ), ")

(define-primitive
  (vector-ref vec index)
  (use scm2host host2scm)
  "prim2((index, vec) => host2scm(vec[1][scm2host(index)])), ")

(define-primitive
  (vector-set! vec index val)
  (use scm2host)
  "prim3((val, index, vec) => vec[1][scm2host(index)] = scm2host(val)), ")


(define x (make-vector 10 0))

(display (vector-ref x 0)) ;; prints 0
(display "\n")

(vector-set! x 5 42) ;; prints 42

(display (vector-ref x 5))
```

For the js host, a foreign object is just a rib with the "6" tag at the 3rd field and some host value inside one of its fields. Here, with the `define-primitive` and the `foreign` feature, we can create an interface to a javascript vector with `make-vector`, `vector-ref`, `vector-set!`. We are still exploring exactly how we want to standardize this to all hosts, especially those that need to garbage collect the vectors once they are not used anymore.

I hope it answers your question !

**Comment by bentaca** [comment]
Thanks for taking this into consideration. Two after thoughts:

1. maybe this is obvious or impossible, but maybe it would be helpful that this foreign variables are immutable

2. in the js implemention there are those 2 conversions for the string type, that seem pretty expensive

## str2scm
```
106: str2scm = (s) => {
    let l = s.length
    let i = l
    let a = NIL
    while (i) a=[s.charCodeAt(--i),a,0];
    return [a,l,3]
}
// )@@
```
## and scm2str
```
217: // @@(feature scm2str
scm2str = (r) => {
    let f = (c) => (c===NIL?"":String.fromCharCode(c[0])+f(c[1]))
    return f(r[0])
}
// )@@
```

Looking the js conversation table maybe you could "foreign" strings handle like numbers? And do simply do this

## for str2scm:

`"string":(x)=>x`
 in:
```
207: // @@(feature host2scm (use list2scm str2scm bool2scm function2scm)
host2scm = (v) => {
  return ({"number":(x)=>x,"boolean":bool2scm,"string":str2scm,"object":list2scm, 'function':function2scm, 'undefined':()=>NIL}[typeof v](v))
}
```

## for scm2str:
change this to:
```
scm2host = (r) => {
  if (typeof r === "number")
    return r 
  let tag = r[2]
  return [scm2list, scm2function, scm2symbol, scm2list, scm2bool][tag](r);
}
 // )@@
```
```
  2   if (typeof r === "number"){
  3    console.log("nuumber");
  4   }else if(typeof r === "string"){
  5    console.log("strrring")
  6   }else{
  7      console.log("convvvert");
  8    }
```

Maybe a solution could be, to make javascript type "string"

**Comment by leo-ard** [comment]
Thanks for the reply ! 

1. I think it's possible to make them immutable, it would need some modification of the rvm making it a little bit bigger. For example, you could modify the `field0-set!`,  `field1-set!` and `field2-set!` primitive to check if the third field contains a 6 (and return an error if it does). But, as we are trying to minimize as much as possible the size of the generated source code, I don't think we should include it by default. If someone wants additional security garanties, they can redefine the primitives and have them.

2. For the Fstrings, it is really similar to the the foreign type described above. The difference between the foreign type and your fstrings, is only that the foreign type are wrapped like this: 

```
foreign_str = (s) => [0, s, 6]
```
Instead of directly having the string. The advantages of wrapping it inside a rib is that you can more easily check for the "foreign" type. It also helps with garbage collection on hosts that doesn't have a garbage collector. We know that if we garbage collect the rib, we can garbage collect the string as well. However, foreign types (or fstrings) have a drawback : we need to define a primitive for each operation that we want to do on them (string-ref, string-sef!, substring, print, write etc..). And all these primitives would need to be created for all hosts. This is why most of the time, we prefer to convert between them to interact with the host langage instead of directly handling the host-string.

**Comment by bentxt** [comment]
Could you please share (no pun intended) some insight on how and where this is implemented? Thanks a lot.
