### ISSUE TITLE
Trouble compiling REPL

### ISSUE THREAD

**Issue by arthurgleckler** [udem-dlteam/ribbit#53]
I've been having a great time trying out Ribbit.  Thank you for writing it and making it available.  It's a real tour de force.

Alas, I've been having trouble getting the REPL to work.  For example, here are my attempts to get it working through assembly language and C:

```
> echo "(repl)"|./rsc -t asm -l max-tc>/tmp/max-tc-repl.asm
> host/asm/asm2exe.sh /tmp/max-tc-repl.asm -o /tmp/max-tc-repl
> /tmp/max-tc-repl
> (define factorial (lambda (n) (if (< n 2) 1 (* n (factorial (- n 1))))))
0
> (factorial 10)
*** type error ()
> > echo "(repl)"|./rsc -t c -l max-tc>/tmp/max-tc-repl.c
> gcc /tmp/max-tc-repl.c
> ./a.out
> (define factorial (lambda (n) (if (< n 2) 1 (* n (factorial (- n 1))))))
0
> (factorial 10)
*** type error ()
> (define add1 (lambda (x) (+ x 1)))
0
> (add1 1)
*** type error ()
>
```

The prebuilt C version, when compiled, works fine with the same input.

I get the same results when I build the REPL this way:

```
> ./rsc -t asm -l max-tc repl-max.scm
> host/asm/asm2exe.sh repl-max.scm.asm -o /tmp/repl-max
> /tmp/repl-max
> (define add1 (lambda (x) (+ x 1)))
0
> (add1 1)
*** type error ()
>
```

Please forgive me if I'm missing something obvious.

**Comment by leo-ard** [comment]
Hi @arthurgleckler, 

Thanks for taking the time to try out ribbit! 

I can reproduce the bug you are talking about for the typed checked version of the REPL. I don't know why this bug is happening, it's probably due to recent changes in the calling protocol inside RVMs. If you want, the non-typed check repl should work just fine : 

```
$ gsi rsc.scm -t asm -l max repl-max.scm -o repl-max.asm
$ nasm repl-max.asm -o repl-max.exe
$ ./repl-max.exe
> (define add1 (lambda (x) (+ x 1)))
0
> (add1 10)
11
> (define factorial (lambda (n) (if (< n 2) 1 (* n (factorial (- n 1))))))
0
> (factorial 10)
3628800
>
```

Note that I am using the `rsc` compiler through `gsi` directly instead of the `./rsc` script. Although not yet documented, this is favored as the `rsc` script only uses a subset of the capabilities of the `rsc.scm` compiler (for example, it cannot parse any annotations inside the RVMs). 

We are currently moving out from the max/min libraries in favor of the r4rs library, which is compliant with the R4RS standard. We will soon update the readme with more details on how to compile and run this REPL. If you want to try it out now, you can do : 

```
$ git checkout dev # all new features are on the dev branch
$ gsi rsc.scm -t asm -l r4rs tests/r4rs/repl/repl.scm -o repl.asm
$ nasm repl.asm -o repl.exe
$ ./repl.exe
              ____________________
             |                    |
             | Welcome to Ribbit! |
             |                    |
    λ        | - Rib the Frog     |
  @...@  --- |____________________|
 (-----)
( >___< )
^^ ~~~ ^^

> (define file (open-input-file "test.data"))
0
> (read file)
(0 1 2)
```

The `dev` branch is still experimental, but feel free to try it out! 

If you have more questions or find other bugs while trying out the r4rs version, feel free to ask them here and I'll answer more promptly.
